/*------------------------------------------------------------
+Author:        Duy Huynh
Company:        Merkle
Description:    
Test Class:     
History
<Date>          <Authors Name>          <Brief Description of Change>
2022/12/01        Duy Huynh         	    Init
------------------------------------------------------------*/
public with sharing class CheckRecursive {
	public static boolean isUpdatedCase = false;
}